import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./global.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

const urbanist = Urbanist({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={
        "scrollbar-thin scrollbar-track-transparent scrollbar-thumb-scampi-500 " +
        urbanist.className
      }
    >
      <Providers>
        <ClerkProvider>
          <body>{children}</body>
        </ClerkProvider>
      </Providers>
    </html>
  );
}
