export const MAJORS = [
  { value: "Biology", label: "Biology" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Computer Science", label: "Computer Science" },
  { value: "Economics", label: "Economics" },
  { value: "Engineering", label: "Engineering" },
  { value: "English Literature", label: "English Literature" },
  { value: "History", label: "History" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Music", label: "Music" },
  { value: "Political Science", label: "Political Science" },
  { value: "Psychology", label: "Psychology" },
  { value: "Sociology", label: "Sociology" },
  { value: "Visual Arts", label: "Visual Arts" },
  { value: "Nursing", label: "Nursing" },
  { value: "Physics", label: "Physics" },
  { value: "Business Administration", label: "Business Administration" },
  { value: "Marketing", label: "Marketing" },
  { value: "Finance", label: "Finance" },
  { value: "Human Resources", label: "Human Resources" },
  { value: "International Relations", label: "International Relations" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "Public Health", label: "Public Health" },
  { value: "Communications", label: "Communications" },
  { value: "Criminal Justice", label: "Criminal Justice" },
  { value: "Education", label: "Education" },
  { value: "Graphic Design", label: "Graphic Design" },
  { value: "Information Technology", label: "Information Technology" },
  { value: "Journalism", label: "Journalism" },
  { value: "Public Administration", label: "Public Administration" },
  { value: "Social Work", label: "Social Work" },
  { value: "Theater Arts", label: "Theater Arts" },
  { value: "Accounting", label: "Accounting" },
  { value: "Agricultural Business", label: "Agricultural Business" },
  { value: "Animal Science", label: "Animal Science" },
  { value: "Anthropology", label: "Anthropology" },
  { value: "Architecture", label: "Architecture" },
  { value: "Art History", label: "Art History" },
  { value: "Biochemistry", label: "Biochemistry" },
  { value: "Biomedical Engineering", label: "Biomedical Engineering" },
  { value: "Chemical Engineering", label: "Chemical Engineering" },
  { value: "Child Development", label: "Child Development" },
  { value: "Civil Engineering", label: "Civil Engineering" },
  { value: "Classics", label: "Classics" },
  { value: "Cognitive Science", label: "Cognitive Science" },
  { value: "Computer Engineering", label: "Computer Engineering" },
  { value: "Construction Management", label: "Construction Management" },
  { value: "Creative Writing", label: "Creative Writing" },
  { value: "Criminal Justice", label: "Criminal Justice" },
  { value: "Dance", label: "Dance" },
  { value: "Drama", label: "Drama" },
  { value: "Early Childhood Education", label: "Early Childhood Education" },
  { value: "Economics", label: "Economics" },
  { value: "Electrical Engineering", label: "Electrical Engineering" },
  { value: "Elementary Education", label: "Elementary Education" },
  { value: "English Literature", label: "English Literature" },
  { value: "Environmental Science", label: "Environmental Science" },
  { value: "Fashion Design", label: "Fashion Design" },
  { value: "Film Studies", label: "Film Studies" },
  { value: "Finance", label: "Finance" },
  { value: "Forensic Science", label: "Forensic Science" },
  { value: "Geology", label: "Geology" },
  { value: "Graphic Design", label: "Graphic Design" },
  { value: "Health Science", label: "Health Science" },
  { value: "History", label: "History" },
  { value: "Hospitality Management", label: "Hospitality Management" },
  { value: "Human Resources", label: "Human Resources" },
  { value: "Industrial Design", label: "Industrial Design" },
  { value: "Information Technology", label: "Information Technology" },
  { value: "Interior Design", label: "Interior Design" },
  { value: "International Relations", label: "International Relations" },
  { value: "Journalism", label: "Journalism" },
  { value: "Kinesiology", label: "Kinesiology" },
  { value: "Linguistics", label: "Linguistics" },
  { value: "Management", label: "Management" },
  { value: "Marketing", label: "Marketing" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Mechanical Engineering", label: "Mechanical Engineering" },
  { value: "Music", label: "Music" },
  { value: "Nursing", label: "Nursing" },
  { value: "Nutrition", label: "Nutrition" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "Photography", label: "Photography" },
  { value: "Physics", label: "Physics" },
  { value: "Political Science", label: "Political Science" },
  { value: "Psychology", label: "Psychology" },
  { value: "Public Health", label: "Public Health" },
  { value: "Public Relations", label: "Public Relations" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Sociology", label: "Sociology" },
  { value: "Software Engineering", label: "Software Engineering" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sports Management", label: "Sports Management" },
  { value: "Statistics", label: "Statistics" },
  { value: "Supply Chain Management", label: "Supply Chain Management" },
  { value: "Theater Arts", label: "Theater Arts" },
  { value: "Urban Planning", label: "Urban Planning" },
  { value: "Veterinary Science", label: "Veterinary Science" },
  { value: "Web Development", label: "Web Development" },
  { value: "Zoology", label: "Zoology" },
  { value: "Actuarial Science", label: "Actuarial Science" },
  { value: "Aerospace Engineering", label: "Aerospace Engineering" },
  { value: "Art Therapy", label: "Art Therapy" },
  { value: "Biotechnology", label: "Biotechnology" },
  { value: "Communications", label: "Communications" },
  { value: "Environmental Engineering", label: "Environmental Engineering" },
  { value: "Healthcare Administration", label: "Healthcare Administration" },
  { value: "Industrial Engineering", label: "Industrial Engineering" },
  { value: "Marine Biology", label: "Marine Biology" },
  { value: "Materials Science", label: "Materials Science" },
  { value: "Neuroscience", label: "Neuroscience" },
  { value: "Occupational Therapy", label: "Occupational Therapy" },
  { value: "Physical Therapy", label: "Physical Therapy" },
  { value: "Public Policy", label: "Public Policy" },
  { value: "Robotics", label: "Robotics" },
  { value: "Sports Medicine", label: "Sports Medicine" },
  { value: "Tourism and Hospitality", label: "Tourism and Hospitality" },
];

export const DEPARTMENTS = [
  { value: "engineering", label: "Department of Engineering" },
  { value: "science", label: "Department of Science" },
  { value: "business", label: "Department of Business" },
  { value: "arts", label: "Department of Arts" },
  { value: "medicine", label: "Department of Medicine" },
  { value: "law", label: "Department of Law" },
  { value: "education", label: "Department of Education" },
  { value: "computer-science", label: "Department of Computer Science" },
  { value: "mathematics", label: "Department of Mathematics" },
  { value: "history", label: "Department of History" },
  { value: "sociology", label: "Department of Sociology" },
  { value: "psychology", label: "Department of Psychology" },
  { value: "physics", label: "Department of Physics" },
  { value: "chemistry", label: "Department of Chemistry" },
  { value: "biology", label: "Department of Biology" },
  { value: "literature", label: "Department of Literature" },
  { value: "music", label: "Department of Music" },
  { value: "geology", label: "Department of Geology" },
  { value: "communication", label: "Department of Communication" },
  { value: "economics", label: "Department of Economics" },
  { value: "philosophy", label: "Department of Philosophy" },
  { value: "anthropology", label: "Department of Anthropology" },
  { value: "linguistics", label: "Department of Linguistics" },
  { value: "political-science", label: "Department of Political Science" },
  {
    value: "environmental-science",
    label: "Department of Environmental Science",
  },
  { value: "architecture", label: "Department of Architecture" },
  { value: "public-health", label: "Department of Public Health" },
  { value: "nutrition", label: "Department of Nutrition" },
  { value: "engineering-physics", label: "Department of Engineering Physics" },
  { value: "fine-arts", label: "Department of Fine Arts" },
  { value: "theater", label: "Department of Theater" },
  { value: "statistics", label: "Department of Statistics" },
  { value: "religious-studies", label: "Department of Religious Studies" },
  { value: "gender-studies", label: "Department of Gender Studies" },
  { value: "urban-planning", label: "Department of Urban Planning" },
  { value: "film-studies", label: "Department of Film Studies" },
  { value: "social-work", label: "Department of Social Work" },
  {
    value: "public-administration",
    label: "Department of Public Administration",
  },
  { value: "astronomy", label: "Department of Astronomy" },
  { value: "robotics", label: "Department of Robotics" },
  { value: "marine-biology", label: "Department of Marine Biology" },
  { value: "linguistics", label: "Department of Linguistics" },
  { value: "data-science", label: "Department of Data Science" },
  { value: "agriculture", label: "Department of Agriculture" },
  { value: "industrial-design", label: "Department of Industrial Design" },
  { value: "biochemistry", label: "Department of Biochemistry" },
  { value: "zoology", label: "Department of Zoology" },
  {
    value: "business-administration",
    label: "Department of Business Administration",
  },
  { value: "earth-sciences", label: "Department of Earth Sciences" },
];
